### ISSUE TITLE
Weather API no longer working

### ISSUE THREAD

**Issue by mcruz85** [ionic-in-action/chapter4#2]
Weather API(https://ionic-in-action-api.herokuapp.com/weather) fails with "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."

**Comment by gnomeontherun** [comment]
Thanks, looks like they now require an API key as of a couple days ago. I'll get this fixed up tonight.

**Comment by gnomeontherun** [comment]
Pushed up an update and deployed to add the key. Thanks again!
